# Generated by Django 4.0.1 on 2022-01-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField()),
                ('picture', models.ImageField(upload_to='pictures/%Y/%m/%d/')),
                ('full_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
            ],
        ),
    ]
